import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import Provider from "@/provider";

const popin = Poppins({
  variable: "--font-poppins",
  weight: "100",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = new QueryClient();
  return (
    <html lang="en" data-theme="light">
      <body className={`${popin.variable}  antialiased`}>
        <Provider>
        {children}
        </Provider>
        
        </body>
    </html>
  );
}
