export const Updatedata = async ({
  id,
  marketing,
  namalokasi,
  alamatlokasi,
  telepon,
  picgedung,
  tanggal,
  operator,
  sistemparkir,
  pk,
  pm,
  fu1,
  fu2,
  fu3,
  kondisi,
  kontrak,
  status,
  keterangan,
}: {
  id: number;
  marketing: string,
  namalokasi: string,
  alamatlokasi: string,
  telepon: string,
  picgedung: string,
  tanggal: string,
  operator: string,
  sistemparkir: string,
  pk: string,
  pm: string,
  fu1: string,
  fu2: string,
  fu3: string,
  kondisi: string,
  kontrak: string,
  status: string,
  keterangan: string,
}) => {
  const res = await fetch(`http://localhost:8080/edit/${id}`, {
    method: "PUT",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      id: id,
      marketing: marketing,
      namalokasi: namalokasi,
      alamatlokasi: alamatlokasi,
      operator: operator,
      sistemparkir: sistemparkir,
      pk: pk, pm: pm,fu1:fu1,fu2:fu2,fu3:fu3, kondisi: kondisi, kontrak: kontrak,
      telepon: telepon,
      picgedung: picgedung,
      tanggal: tanggal,
      status: status,
      keterangan: keterangan,
    }),
  });
  if (!res.ok) throw new Error("nextjs gagal update data");
  return res.json();
};
